"""Explicit PyArrow schemas for normalized Phase 3A tables."""

from __future__ import annotations

import pyarrow as pa  # type: ignore[import-untyped]

TRADE_COLUMNS = [
    "normalized_schema_version",
    "normalized_event_id",
    "validated_dataset_manifest_id",
    "validated_dataset_manifest_sha256",
    "paired_collection_id",
    "venue",
    "canonical_instrument",
    "venue_symbol",
    "session_id",
    "connection_epoch",
    "source_channel",
    "source_message_type",
    "source_shard_relative_path",
    "source_shard_sha256",
    "source_raw_record_index",
    "normalized_child_index",
    "source_raw_frame_sha256",
    "local_receipt_ts",
    "exchange_ts",
    "trade_id",
    "price",
    "quantity",
    "side",
    "side_semantics",
    "source_trade_id",
    "source_sequence",
    "source_checksum",
    "is_raw_frame_duplicate",
    "raw_frame_duplicate_count",
    "raw_frame_duplicate_occurrence_index",
]

TOP_OF_BOOK_COLUMNS = [
    "normalized_schema_version",
    "normalized_event_id",
    "validated_dataset_manifest_id",
    "validated_dataset_manifest_sha256",
    "paired_collection_id",
    "venue",
    "canonical_instrument",
    "venue_symbol",
    "session_id",
    "connection_epoch",
    "source_channel",
    "source_message_type",
    "source_shard_relative_path",
    "source_shard_sha256",
    "source_raw_record_index",
    "normalized_child_index",
    "source_raw_frame_sha256",
    "local_receipt_ts",
    "exchange_ts",
    "bid_price",
    "bid_size",
    "ask_price",
    "ask_size",
    "source_sequence",
    "source_checksum",
    "is_raw_frame_duplicate",
    "raw_frame_duplicate_count",
    "raw_frame_duplicate_occurrence_index",
]

OUTCOME_COLUMNS = [
    "normalized_schema_version",
    "validated_dataset_manifest_id",
    "validated_dataset_manifest_sha256",
    "paired_collection_id",
    "venue",
    "canonical_instrument",
    "venue_symbol",
    "session_id",
    "connection_epoch",
    "source_shard_relative_path",
    "source_shard_sha256",
    "source_raw_record_index",
    "source_raw_frame_sha256",
    "local_receipt_ts",
    "frame_type",
    "source_message_type",
    "source_channel",
    "normalization_outcome",
    "normalized_trade_row_count",
    "normalized_bbo_row_count",
    "normalized_total_row_count",
    "parse_status",
    "parse_error_type",
    "parse_error_message",
    "unsupported_reason",
    "is_raw_frame_duplicate",
    "raw_frame_duplicate_count",
    "raw_frame_duplicate_occurrence_index",
]


def trade_schema(*, precision: int, scale: int) -> pa.Schema:
    decimal = pa.decimal128(precision, scale)
    return pa.schema(
        [
            pa.field("normalized_schema_version", pa.string(), nullable=False),
            pa.field("normalized_event_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_sha256", pa.string(), nullable=False),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("venue", pa.string(), nullable=False),
            pa.field("canonical_instrument", pa.string(), nullable=False),
            pa.field("venue_symbol", pa.string(), nullable=False),
            pa.field("session_id", pa.string(), nullable=False),
            pa.field("connection_epoch", pa.int32(), nullable=False),
            pa.field("source_channel", pa.string(), nullable=False),
            pa.field("source_message_type", pa.string(), nullable=False),
            pa.field("source_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_record_index", pa.int64(), nullable=False),
            pa.field("normalized_child_index", pa.int32(), nullable=False),
            pa.field("source_raw_frame_sha256", pa.string(), nullable=False),
            pa.field("local_receipt_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("exchange_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("trade_id", pa.string(), nullable=False),
            pa.field("price", decimal, nullable=False),
            pa.field("quantity", decimal, nullable=False),
            pa.field("side", pa.string(), nullable=False),
            pa.field("side_semantics", pa.string(), nullable=False),
            pa.field("source_trade_id", pa.string(), nullable=True),
            pa.field("source_sequence", pa.string(), nullable=True),
            pa.field("source_checksum", pa.string(), nullable=True),
            pa.field("is_raw_frame_duplicate", pa.bool_(), nullable=False),
            pa.field("raw_frame_duplicate_count", pa.int32(), nullable=False),
            pa.field("raw_frame_duplicate_occurrence_index", pa.int32(), nullable=False),
        ]
    )


def top_of_book_schema(*, precision: int, scale: int) -> pa.Schema:
    decimal = pa.decimal128(precision, scale)
    return pa.schema(
        [
            pa.field("normalized_schema_version", pa.string(), nullable=False),
            pa.field("normalized_event_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_sha256", pa.string(), nullable=False),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("venue", pa.string(), nullable=False),
            pa.field("canonical_instrument", pa.string(), nullable=False),
            pa.field("venue_symbol", pa.string(), nullable=False),
            pa.field("session_id", pa.string(), nullable=False),
            pa.field("connection_epoch", pa.int32(), nullable=False),
            pa.field("source_channel", pa.string(), nullable=False),
            pa.field("source_message_type", pa.string(), nullable=False),
            pa.field("source_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_record_index", pa.int64(), nullable=False),
            pa.field("normalized_child_index", pa.int32(), nullable=False),
            pa.field("source_raw_frame_sha256", pa.string(), nullable=False),
            pa.field("local_receipt_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("exchange_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("bid_price", decimal, nullable=False),
            pa.field("bid_size", decimal, nullable=False),
            pa.field("ask_price", decimal, nullable=False),
            pa.field("ask_size", decimal, nullable=False),
            pa.field("source_sequence", pa.string(), nullable=True),
            pa.field("source_checksum", pa.string(), nullable=True),
            pa.field("is_raw_frame_duplicate", pa.bool_(), nullable=False),
            pa.field("raw_frame_duplicate_count", pa.int32(), nullable=False),
            pa.field("raw_frame_duplicate_occurrence_index", pa.int32(), nullable=False),
        ]
    )


def outcome_schema() -> pa.Schema:
    return pa.schema(
        [
            pa.field("normalized_schema_version", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_sha256", pa.string(), nullable=False),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("venue", pa.string(), nullable=False),
            pa.field("canonical_instrument", pa.string(), nullable=False),
            pa.field("venue_symbol", pa.string(), nullable=False),
            pa.field("session_id", pa.string(), nullable=False),
            pa.field("connection_epoch", pa.int32(), nullable=False),
            pa.field("source_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_record_index", pa.int64(), nullable=False),
            pa.field("source_raw_frame_sha256", pa.string(), nullable=False),
            pa.field("local_receipt_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("frame_type", pa.string(), nullable=False),
            pa.field("source_message_type", pa.string(), nullable=True),
            pa.field("source_channel", pa.string(), nullable=True),
            pa.field("normalization_outcome", pa.string(), nullable=False),
            pa.field("normalized_trade_row_count", pa.int32(), nullable=False),
            pa.field("normalized_bbo_row_count", pa.int32(), nullable=False),
            pa.field("normalized_total_row_count", pa.int32(), nullable=False),
            pa.field("parse_status", pa.string(), nullable=False),
            pa.field("parse_error_type", pa.string(), nullable=True),
            pa.field("parse_error_message", pa.string(), nullable=True),
            pa.field("unsupported_reason", pa.string(), nullable=True),
            pa.field("is_raw_frame_duplicate", pa.bool_(), nullable=False),
            pa.field("raw_frame_duplicate_count", pa.int32(), nullable=False),
            pa.field("raw_frame_duplicate_occurrence_index", pa.int32(), nullable=False),
        ]
    )
