"""Explicit PyArrow schemas for normalized research tables."""

from __future__ import annotations

import pyarrow as pa  # type: ignore[import-untyped]

TRADE_COLUMNS = [
    "dataset_snapshot_id",
    "source_catalog_id",
    "source_catalog_hash",
    "normalized_schema_version",
    "normalization_config_hash",
    "normalized_event_id",
    "source_event_id",
    "campaign_id",
    "campaign_role",
    "slot_id",
    "slot_type",
    "campaign_attempt_id",
    "time_bucket",
    "validated_campaign_manifest_id",
    "validated_campaign_manifest_sha256",
    "validated_dataset_manifest_id",
    "validated_dataset_manifest_sha256",
    "paired_collection_id",
    "venue",
    "canonical_instrument",
    "venue_symbol",
    "session_id",
    "venue_session_id",
    "connection_epoch",
    "source_channel",
    "source_message_type",
    "source_shard_relative_path",
    "source_raw_shard_relative_path",
    "source_shard_sha256",
    "source_raw_shard_sha256",
    "source_raw_record_index",
    "source_record_index",
    "normalized_child_index",
    "source_raw_frame_sha256",
    "local_receipt_ts",
    "receipt_timestamp_utc",
    "original_receipt_timestamp",
    "exchange_ts",
    "exchange_timestamp_utc",
    "original_exchange_timestamp",
    "has_exchange_timestamp",
    "exchange_timestamp_semantics",
    "receipt_timestamp_semantics",
    "trade_id",
    "venue_trade_id",
    "price",
    "quantity",
    "notional",
    "side",
    "reported_side",
    "normalized_side",
    "side_semantics",
    "aggressor_side_interpretation_status",
    "source_trade_id",
    "source_sequence",
    "source_checksum",
    "is_raw_frame_duplicate",
    "duplicate_classification",
    "raw_frame_duplicate_count",
    "raw_frame_duplicate_occurrence_index",
    "source_session_manifest_sha256",
    "source_quality_report_sha256",
    "paired_quality_report_sha256",
    "collection_runtime_git_commit",
    "quality_code_git_commit",
    "quality_policy_version",
    "parser_version",
    "normalization_warning_codes",
]

TOP_OF_BOOK_COLUMNS = [
    "dataset_snapshot_id",
    "source_catalog_id",
    "source_catalog_hash",
    "normalized_schema_version",
    "normalization_config_hash",
    "normalized_event_id",
    "source_event_id",
    "campaign_id",
    "campaign_role",
    "slot_id",
    "slot_type",
    "campaign_attempt_id",
    "time_bucket",
    "validated_campaign_manifest_id",
    "validated_campaign_manifest_sha256",
    "validated_dataset_manifest_id",
    "validated_dataset_manifest_sha256",
    "paired_collection_id",
    "venue",
    "canonical_instrument",
    "venue_symbol",
    "session_id",
    "venue_session_id",
    "connection_epoch",
    "source_channel",
    "source_message_type",
    "source_shard_relative_path",
    "source_raw_shard_relative_path",
    "source_shard_sha256",
    "source_raw_shard_sha256",
    "source_raw_record_index",
    "source_record_index",
    "normalized_child_index",
    "source_raw_frame_sha256",
    "local_receipt_ts",
    "receipt_timestamp_utc",
    "original_receipt_timestamp",
    "exchange_ts",
    "exchange_timestamp_utc",
    "original_exchange_timestamp",
    "has_exchange_timestamp",
    "exchange_timestamp_semantics",
    "receipt_timestamp_semantics",
    "bid_price",
    "bid_size",
    "ask_price",
    "ask_size",
    "midprice",
    "spread",
    "relative_spread",
    "spread_basis_points",
    "quoted_depth",
    "bid_ask_imbalance",
    "locked_market_indicator",
    "crossed_market_indicator",
    "quote_change_indicator",
    "source_sequence",
    "source_checksum",
    "is_raw_frame_duplicate",
    "duplicate_classification",
    "raw_frame_duplicate_count",
    "raw_frame_duplicate_occurrence_index",
    "source_session_manifest_sha256",
    "source_quality_report_sha256",
    "paired_quality_report_sha256",
    "collection_runtime_git_commit",
    "quality_code_git_commit",
    "quality_policy_version",
    "parser_version",
    "normalization_warning_codes",
]

OUTCOME_COLUMNS = [
    "dataset_snapshot_id",
    "source_catalog_id",
    "source_catalog_hash",
    "normalized_schema_version",
    "normalization_config_hash",
    "campaign_id",
    "campaign_role",
    "slot_id",
    "slot_type",
    "campaign_attempt_id",
    "time_bucket",
    "validated_campaign_manifest_id",
    "validated_campaign_manifest_sha256",
    "validated_dataset_manifest_id",
    "validated_dataset_manifest_sha256",
    "paired_collection_id",
    "venue",
    "canonical_instrument",
    "venue_symbol",
    "session_id",
    "venue_session_id",
    "connection_epoch",
    "source_shard_relative_path",
    "source_raw_shard_relative_path",
    "source_shard_sha256",
    "source_raw_shard_sha256",
    "source_raw_record_index",
    "source_record_index",
    "source_raw_frame_sha256",
    "local_receipt_ts",
    "receipt_timestamp_utc",
    "original_receipt_timestamp",
    "frame_type",
    "source_message_type",
    "source_channel",
    "normalization_outcome",
    "normalized_trade_row_count",
    "normalized_bbo_row_count",
    "normalized_total_row_count",
    "parse_status",
    "parse_error_type",
    "parse_error_message",
    "unsupported_reason",
    "is_raw_frame_duplicate",
    "duplicate_classification",
    "raw_frame_duplicate_count",
    "raw_frame_duplicate_occurrence_index",
    "source_session_manifest_sha256",
    "source_quality_report_sha256",
    "paired_quality_report_sha256",
    "collection_runtime_git_commit",
    "quality_code_git_commit",
    "quality_policy_version",
    "parser_version",
]

SESSION_METADATA_COLUMNS = [
    "dataset_snapshot_id",
    "source_catalog_id",
    "campaign_id",
    "campaign_role",
    "campaign_attempt_id",
    "slot_id",
    "slot_type",
    "time_bucket",
    "paired_collection_id",
    "venue",
    "venue_session_id",
    "planned_start_utc",
    "actual_started_at",
    "actual_completed_at",
    "requested_duration_seconds",
    "actual_duration_seconds",
    "accepted_paired_overlap_seconds",
    "effective_message_limit",
    "stop_reason",
    "frame_count",
    "trade_count",
    "top_of_book_count",
    "archive_validation_state",
    "source_session_manifest_sha256",
    "source_quality_report_sha256",
    "paired_quality_report_sha256",
    "collection_runtime_git_commit",
    "quality_code_git_commit",
    "quality_policy_version",
    "analysis_calendar_date",
    "normalization_disposition",
    "normalized_trade_row_count",
    "normalized_top_of_book_row_count",
    "diagnostic_row_count",
]

ATTEMPT_METADATA_COLUMNS = [
    "dataset_snapshot_id",
    "source_catalog_id",
    "campaign_id",
    "campaign_role",
    "campaign_attempt_id",
    "slot_id",
    "slot_type",
    "time_bucket",
    "paired_collection_id",
    "validated_pair_manifest_id",
    "validated_pair_manifest_sha256",
    "coinbase_session_id",
    "kraken_session_id",
    "planned_start_utc",
    "actual_started_at",
    "actual_completed_at",
    "requested_duration_seconds",
    "accepted_paired_overlap_seconds",
    "paired_quality_report_sha256",
    "collection_runtime_git_commit",
    "quality_code_git_commit",
    "quality_policy_version",
    "analysis_calendar_date",
    "normalization_disposition",
    "normalized_trade_row_count",
    "normalized_top_of_book_row_count",
    "diagnostic_row_count",
]


def trade_schema(*, precision: int, scale: int) -> pa.Schema:
    decimal = pa.decimal128(precision, scale)
    return pa.schema(
        [
            pa.field("dataset_snapshot_id", pa.string(), nullable=True),
            pa.field("source_catalog_id", pa.string(), nullable=True),
            pa.field("source_catalog_hash", pa.string(), nullable=True),
            pa.field("normalized_schema_version", pa.string(), nullable=False),
            pa.field("normalization_config_hash", pa.string(), nullable=False),
            pa.field("normalized_event_id", pa.string(), nullable=False),
            pa.field("source_event_id", pa.string(), nullable=False),
            pa.field("campaign_id", pa.string(), nullable=True),
            pa.field("campaign_role", pa.string(), nullable=True),
            pa.field("slot_id", pa.string(), nullable=True),
            pa.field("slot_type", pa.string(), nullable=True),
            pa.field("campaign_attempt_id", pa.string(), nullable=True),
            pa.field("time_bucket", pa.string(), nullable=True),
            pa.field("validated_campaign_manifest_id", pa.string(), nullable=True),
            pa.field("validated_campaign_manifest_sha256", pa.string(), nullable=True),
            pa.field("validated_dataset_manifest_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_sha256", pa.string(), nullable=False),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("venue", pa.string(), nullable=False),
            pa.field("canonical_instrument", pa.string(), nullable=False),
            pa.field("venue_symbol", pa.string(), nullable=False),
            pa.field("session_id", pa.string(), nullable=False),
            pa.field("venue_session_id", pa.string(), nullable=False),
            pa.field("connection_epoch", pa.int32(), nullable=False),
            pa.field("source_channel", pa.string(), nullable=False),
            pa.field("source_message_type", pa.string(), nullable=False),
            pa.field("source_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_raw_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_record_index", pa.int64(), nullable=False),
            pa.field("source_record_index", pa.int64(), nullable=False),
            pa.field("normalized_child_index", pa.int32(), nullable=False),
            pa.field("source_raw_frame_sha256", pa.string(), nullable=False),
            pa.field("local_receipt_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("receipt_timestamp_utc", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("original_receipt_timestamp", pa.string(), nullable=False),
            pa.field("exchange_ts", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("exchange_timestamp_utc", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("original_exchange_timestamp", pa.string(), nullable=True),
            pa.field("has_exchange_timestamp", pa.bool_(), nullable=False),
            pa.field("exchange_timestamp_semantics", pa.string(), nullable=False),
            pa.field("receipt_timestamp_semantics", pa.string(), nullable=False),
            pa.field("trade_id", pa.string(), nullable=False),
            pa.field("venue_trade_id", pa.string(), nullable=True),
            pa.field("price", decimal, nullable=False),
            pa.field("quantity", decimal, nullable=False),
            pa.field("notional", decimal, nullable=False),
            pa.field("side", pa.string(), nullable=False),
            pa.field("reported_side", pa.string(), nullable=True),
            pa.field("normalized_side", pa.string(), nullable=False),
            pa.field("side_semantics", pa.string(), nullable=False),
            pa.field("aggressor_side_interpretation_status", pa.string(), nullable=False),
            pa.field("source_trade_id", pa.string(), nullable=True),
            pa.field("source_sequence", pa.string(), nullable=True),
            pa.field("source_checksum", pa.string(), nullable=True),
            pa.field("is_raw_frame_duplicate", pa.bool_(), nullable=False),
            pa.field("duplicate_classification", pa.string(), nullable=False),
            pa.field("raw_frame_duplicate_count", pa.int32(), nullable=False),
            pa.field("raw_frame_duplicate_occurrence_index", pa.int32(), nullable=False),
            pa.field("source_session_manifest_sha256", pa.string(), nullable=False),
            pa.field("source_quality_report_sha256", pa.string(), nullable=False),
            pa.field("paired_quality_report_sha256", pa.string(), nullable=False),
            pa.field("collection_runtime_git_commit", pa.string(), nullable=False),
            pa.field("quality_code_git_commit", pa.string(), nullable=False),
            pa.field("quality_policy_version", pa.string(), nullable=False),
            pa.field("parser_version", pa.string(), nullable=False),
            pa.field("normalization_warning_codes", pa.list_(pa.string()), nullable=False),
        ]
    )


def top_of_book_schema(*, precision: int, scale: int) -> pa.Schema:
    decimal = pa.decimal128(precision, scale)
    return pa.schema(
        [
            pa.field("dataset_snapshot_id", pa.string(), nullable=True),
            pa.field("source_catalog_id", pa.string(), nullable=True),
            pa.field("source_catalog_hash", pa.string(), nullable=True),
            pa.field("normalized_schema_version", pa.string(), nullable=False),
            pa.field("normalization_config_hash", pa.string(), nullable=False),
            pa.field("normalized_event_id", pa.string(), nullable=False),
            pa.field("source_event_id", pa.string(), nullable=False),
            pa.field("campaign_id", pa.string(), nullable=True),
            pa.field("campaign_role", pa.string(), nullable=True),
            pa.field("slot_id", pa.string(), nullable=True),
            pa.field("slot_type", pa.string(), nullable=True),
            pa.field("campaign_attempt_id", pa.string(), nullable=True),
            pa.field("time_bucket", pa.string(), nullable=True),
            pa.field("validated_campaign_manifest_id", pa.string(), nullable=True),
            pa.field("validated_campaign_manifest_sha256", pa.string(), nullable=True),
            pa.field("validated_dataset_manifest_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_sha256", pa.string(), nullable=False),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("venue", pa.string(), nullable=False),
            pa.field("canonical_instrument", pa.string(), nullable=False),
            pa.field("venue_symbol", pa.string(), nullable=False),
            pa.field("session_id", pa.string(), nullable=False),
            pa.field("venue_session_id", pa.string(), nullable=False),
            pa.field("connection_epoch", pa.int32(), nullable=False),
            pa.field("source_channel", pa.string(), nullable=False),
            pa.field("source_message_type", pa.string(), nullable=False),
            pa.field("source_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_raw_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_record_index", pa.int64(), nullable=False),
            pa.field("source_record_index", pa.int64(), nullable=False),
            pa.field("normalized_child_index", pa.int32(), nullable=False),
            pa.field("source_raw_frame_sha256", pa.string(), nullable=False),
            pa.field("local_receipt_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("receipt_timestamp_utc", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("original_receipt_timestamp", pa.string(), nullable=False),
            pa.field("exchange_ts", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("exchange_timestamp_utc", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("original_exchange_timestamp", pa.string(), nullable=True),
            pa.field("has_exchange_timestamp", pa.bool_(), nullable=False),
            pa.field("exchange_timestamp_semantics", pa.string(), nullable=False),
            pa.field("receipt_timestamp_semantics", pa.string(), nullable=False),
            pa.field("bid_price", decimal, nullable=False),
            pa.field("bid_size", decimal, nullable=False),
            pa.field("ask_price", decimal, nullable=False),
            pa.field("ask_size", decimal, nullable=False),
            pa.field("midprice", decimal, nullable=False),
            pa.field("spread", decimal, nullable=False),
            pa.field("relative_spread", decimal, nullable=True),
            pa.field("spread_basis_points", decimal, nullable=True),
            pa.field("quoted_depth", decimal, nullable=False),
            pa.field("bid_ask_imbalance", decimal, nullable=True),
            pa.field("locked_market_indicator", pa.bool_(), nullable=False),
            pa.field("crossed_market_indicator", pa.bool_(), nullable=False),
            pa.field("quote_change_indicator", pa.string(), nullable=False),
            pa.field("source_sequence", pa.string(), nullable=True),
            pa.field("source_checksum", pa.string(), nullable=True),
            pa.field("is_raw_frame_duplicate", pa.bool_(), nullable=False),
            pa.field("duplicate_classification", pa.string(), nullable=False),
            pa.field("raw_frame_duplicate_count", pa.int32(), nullable=False),
            pa.field("raw_frame_duplicate_occurrence_index", pa.int32(), nullable=False),
            pa.field("source_session_manifest_sha256", pa.string(), nullable=False),
            pa.field("source_quality_report_sha256", pa.string(), nullable=False),
            pa.field("paired_quality_report_sha256", pa.string(), nullable=False),
            pa.field("collection_runtime_git_commit", pa.string(), nullable=False),
            pa.field("quality_code_git_commit", pa.string(), nullable=False),
            pa.field("quality_policy_version", pa.string(), nullable=False),
            pa.field("parser_version", pa.string(), nullable=False),
            pa.field("normalization_warning_codes", pa.list_(pa.string()), nullable=False),
        ]
    )


def outcome_schema() -> pa.Schema:
    return pa.schema(
        [
            pa.field("dataset_snapshot_id", pa.string(), nullable=True),
            pa.field("source_catalog_id", pa.string(), nullable=True),
            pa.field("source_catalog_hash", pa.string(), nullable=True),
            pa.field("normalized_schema_version", pa.string(), nullable=False),
            pa.field("normalization_config_hash", pa.string(), nullable=False),
            pa.field("campaign_id", pa.string(), nullable=True),
            pa.field("campaign_role", pa.string(), nullable=True),
            pa.field("slot_id", pa.string(), nullable=True),
            pa.field("slot_type", pa.string(), nullable=True),
            pa.field("campaign_attempt_id", pa.string(), nullable=True),
            pa.field("time_bucket", pa.string(), nullable=True),
            pa.field("validated_campaign_manifest_id", pa.string(), nullable=True),
            pa.field("validated_campaign_manifest_sha256", pa.string(), nullable=True),
            pa.field("validated_dataset_manifest_id", pa.string(), nullable=False),
            pa.field("validated_dataset_manifest_sha256", pa.string(), nullable=False),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("venue", pa.string(), nullable=False),
            pa.field("canonical_instrument", pa.string(), nullable=False),
            pa.field("venue_symbol", pa.string(), nullable=False),
            pa.field("session_id", pa.string(), nullable=False),
            pa.field("venue_session_id", pa.string(), nullable=False),
            pa.field("connection_epoch", pa.int32(), nullable=False),
            pa.field("source_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_raw_shard_relative_path", pa.string(), nullable=False),
            pa.field("source_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_shard_sha256", pa.string(), nullable=False),
            pa.field("source_raw_record_index", pa.int64(), nullable=False),
            pa.field("source_record_index", pa.int64(), nullable=False),
            pa.field("source_raw_frame_sha256", pa.string(), nullable=False),
            pa.field("local_receipt_ts", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("receipt_timestamp_utc", pa.timestamp("ns", tz="UTC"), nullable=False),
            pa.field("original_receipt_timestamp", pa.string(), nullable=False),
            pa.field("frame_type", pa.string(), nullable=False),
            pa.field("source_message_type", pa.string(), nullable=True),
            pa.field("source_channel", pa.string(), nullable=True),
            pa.field("normalization_outcome", pa.string(), nullable=False),
            pa.field("normalized_trade_row_count", pa.int32(), nullable=False),
            pa.field("normalized_bbo_row_count", pa.int32(), nullable=False),
            pa.field("normalized_total_row_count", pa.int32(), nullable=False),
            pa.field("parse_status", pa.string(), nullable=False),
            pa.field("parse_error_type", pa.string(), nullable=True),
            pa.field("parse_error_message", pa.string(), nullable=True),
            pa.field("unsupported_reason", pa.string(), nullable=True),
            pa.field("is_raw_frame_duplicate", pa.bool_(), nullable=False),
            pa.field("duplicate_classification", pa.string(), nullable=False),
            pa.field("raw_frame_duplicate_count", pa.int32(), nullable=False),
            pa.field("raw_frame_duplicate_occurrence_index", pa.int32(), nullable=False),
            pa.field("source_session_manifest_sha256", pa.string(), nullable=False),
            pa.field("source_quality_report_sha256", pa.string(), nullable=False),
            pa.field("paired_quality_report_sha256", pa.string(), nullable=False),
            pa.field("collection_runtime_git_commit", pa.string(), nullable=False),
            pa.field("quality_code_git_commit", pa.string(), nullable=False),
            pa.field("quality_policy_version", pa.string(), nullable=False),
            pa.field("parser_version", pa.string(), nullable=False),
        ]
    )


def session_metadata_schema() -> pa.Schema:
    decimal = pa.decimal128(38, 18)
    return pa.schema(
        [
            pa.field("dataset_snapshot_id", pa.string(), nullable=True),
            pa.field("source_catalog_id", pa.string(), nullable=True),
            pa.field("campaign_id", pa.string(), nullable=True),
            pa.field("campaign_role", pa.string(), nullable=True),
            pa.field("campaign_attempt_id", pa.string(), nullable=True),
            pa.field("slot_id", pa.string(), nullable=True),
            pa.field("slot_type", pa.string(), nullable=True),
            pa.field("time_bucket", pa.string(), nullable=True),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("venue", pa.string(), nullable=False),
            pa.field("venue_session_id", pa.string(), nullable=False),
            pa.field("planned_start_utc", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("actual_started_at", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("actual_completed_at", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("requested_duration_seconds", decimal, nullable=True),
            pa.field("actual_duration_seconds", decimal, nullable=True),
            pa.field("accepted_paired_overlap_seconds", decimal, nullable=True),
            pa.field("effective_message_limit", pa.int64(), nullable=True),
            pa.field("stop_reason", pa.string(), nullable=True),
            pa.field("frame_count", pa.int64(), nullable=False),
            pa.field("trade_count", pa.int64(), nullable=False),
            pa.field("top_of_book_count", pa.int64(), nullable=False),
            pa.field("archive_validation_state", pa.string(), nullable=False),
            pa.field("source_session_manifest_sha256", pa.string(), nullable=False),
            pa.field("source_quality_report_sha256", pa.string(), nullable=False),
            pa.field("paired_quality_report_sha256", pa.string(), nullable=False),
            pa.field("collection_runtime_git_commit", pa.string(), nullable=False),
            pa.field("quality_code_git_commit", pa.string(), nullable=False),
            pa.field("quality_policy_version", pa.string(), nullable=False),
            pa.field("analysis_calendar_date", pa.string(), nullable=True),
            pa.field("normalization_disposition", pa.string(), nullable=False),
            pa.field("normalized_trade_row_count", pa.int64(), nullable=False),
            pa.field("normalized_top_of_book_row_count", pa.int64(), nullable=False),
            pa.field("diagnostic_row_count", pa.int64(), nullable=False),
        ]
    )


def attempt_metadata_schema() -> pa.Schema:
    decimal = pa.decimal128(38, 18)
    return pa.schema(
        [
            pa.field("dataset_snapshot_id", pa.string(), nullable=True),
            pa.field("source_catalog_id", pa.string(), nullable=True),
            pa.field("campaign_id", pa.string(), nullable=True),
            pa.field("campaign_role", pa.string(), nullable=True),
            pa.field("campaign_attempt_id", pa.string(), nullable=True),
            pa.field("slot_id", pa.string(), nullable=True),
            pa.field("slot_type", pa.string(), nullable=True),
            pa.field("time_bucket", pa.string(), nullable=True),
            pa.field("paired_collection_id", pa.string(), nullable=False),
            pa.field("validated_pair_manifest_id", pa.string(), nullable=False),
            pa.field("validated_pair_manifest_sha256", pa.string(), nullable=False),
            pa.field("coinbase_session_id", pa.string(), nullable=True),
            pa.field("kraken_session_id", pa.string(), nullable=True),
            pa.field("planned_start_utc", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("actual_started_at", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("actual_completed_at", pa.timestamp("ns", tz="UTC"), nullable=True),
            pa.field("requested_duration_seconds", decimal, nullable=True),
            pa.field("accepted_paired_overlap_seconds", decimal, nullable=True),
            pa.field("paired_quality_report_sha256", pa.string(), nullable=True),
            pa.field("collection_runtime_git_commit", pa.string(), nullable=True),
            pa.field("quality_code_git_commit", pa.string(), nullable=True),
            pa.field("quality_policy_version", pa.string(), nullable=True),
            pa.field("analysis_calendar_date", pa.string(), nullable=True),
            pa.field("normalization_disposition", pa.string(), nullable=False),
            pa.field("normalized_trade_row_count", pa.int64(), nullable=False),
            pa.field("normalized_top_of_book_row_count", pa.int64(), nullable=False),
            pa.field("diagnostic_row_count", pa.int64(), nullable=False),
        ]
    )
