repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python -m ruff check
        language: system
        pass_filenames: false
        types_or: [python, pyi]
        args: [src, tests]

      - id: mypy
        name: mypy
        entry: python -m mypy
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        types_or: [python, pyi]

